name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.x

      - name: Set .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          cat .npmrc

      - run: npm ci --legacy-peer-deps

      - run: npx nx format:check
      - run: npx nx affected -t lint --quiet --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3

      - name: Cleanup .npmrc
        run: rm .npmrc
